"""Canonical enums for the deterministic Kriegsspiel engine."""

from enum import Enum


class Side(str, Enum):
    BLUE = "BLUE"
    RED = "RED"
    NEUTRAL = "NEUTRAL"


class Affiliation(str, Enum):
    BLUE = "BLUE"
    RED_RU = "RED_RU"
    RED_CN = "RED_CN"
    RED_IRR = "RED_IRR"
    OPFOR = "OPFOR"


class Category(str, Enum):
    # Legacy engine categories (kept for compatibility)
    MANEUVER = "MANEUVER"
    FIRES = "FIRES"
    AIR_DEFENSE = "AIR_DEFENSE"
    SUSTAINMENT = "SUSTAINMENT"
    ENABLER = "ENABLER"
    # V3 unit-library categories
    AIR = "AIR"
    LIGHT_INFANTRY = "LIGHT_INFANTRY"
    ARMOR = "ARMOR"
    TRANSPORT = "TRANSPORT"
    MARITIME_CARGO = "MARITIME_CARGO"
    MARITIME_BATTLE = "MARITIME_BATTLE"
    SPECIAL = "SPECIAL"
    ARTILLERY = "ARTILLERY"
    IRREGULAR = "IRREGULAR"


class Domain(str, Enum):
    # Legacy engine domains
    GROUND = "GROUND"
    MARITIME = "MARITIME"
    AIR = "AIR"
    CYBER = "CYBER"
    SPACE = "SPACE"
    # V3 maneuver types
    LAND = "LAND"
    SEA = "SEA"
    SUBSURFACE = "SUBSURFACE"
    AMPHIBIOUS = "AMPHIBIOUS"


class Readiness(str, Enum):
    FULLY_OPERATIONAL = "FULLY_OPERATIONAL"
    DEGRADED = "DEGRADED"
    SUPPRESSED = "SUPPRESSED"
    DESTROYED = "DESTROYED"


class TerrainBase(str, Enum):
    OPEN = "OPEN"
    FOREST = "FOREST"
    URBAN = "URBAN"
    WATER = "WATER"
    MOUNTAIN = "MOUNTAIN"
    SWAMP = "SWAMP"
    IMPASSABLE = "IMPASSABLE"


class TerrainFeature(str, Enum):
    RIVER = "RIVER"
    WATER_DEEP = "WATER_DEEP"
    BRIDGE = "BRIDGE"
    FORD = "FORD"
    ROAD = "ROAD"
    RAIL = "RAIL"
    FORTIFIED = "FORTIFIED"
    URBAN_DENSE = "URBAN_DENSE"
    URBAN_SPARSE = "URBAN_SPARSE"
    OBJECTIVE = "OBJECTIVE"


class Posture(str, Enum):
    OFFENSIVE = "OFFENSIVE"
    DEFENSIVE = "DEFENSIVE"
    MOVING = "MOVING"
    SCREENING = "SCREENING"
    RESUPPLYING = "RESUPPLYING"


class ActionType(str, Enum):
    MOVE = "MOVE"
    ASSAULT = "ASSAULT"
    DEFEND = "DEFEND"
    RECON = "RECON"
    SUPPLY = "SUPPLY"
    HOLD = "HOLD"


class EventType(str, Enum):
    UNIT_MOVED = "UNIT_MOVED"
    UNIT_MOVE_BLOCKED = "UNIT_MOVE_BLOCKED"
    CROSSING_USED = "CROSSING_USED"
    COMBAT_RESOLVED = "COMBAT_RESOLVED"
    UNIT_DESTROYED = "UNIT_DESTROYED"
    UNIT_SUPPRESSED = "UNIT_SUPPRESSED"
    UNIT_DEGRADED = "UNIT_DEGRADED"
    SUPPLY_CONSUMED = "SUPPLY_CONSUMED"
    SUPPLY_DELIVERED = "SUPPLY_DELIVERED"
    UNIT_ISOLATED = "UNIT_ISOLATED"
    ATTRITION_APPLIED = "ATTRITION_APPLIED"
    CONTROL_CHANGED = "CONTROL_CHANGED"
    OBJECTIVE_TAKEN = "OBJECTIVE_TAKEN"
    TURN_ADVANCED = "TURN_ADVANCED"
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"


class ReasonCode(str, Enum):
    MOV_OK = "MOV_OK"
    MOV_TERRAIN_IMPASSABLE = "MOV_TERRAIN_IMPASSABLE"
    MOV_INSUFFICIENT_ALLOWANCE = "MOV_INSUFFICIENT_ALLOWANCE"
    MOV_BLOCKED_BY_ENEMY = "MOV_BLOCKED_BY_ENEMY"
    MOV_NO_PATH = "MOV_NO_PATH"
    MOV_CROSSING_REQUIRED = "MOV_CROSSING_REQUIRED"
    MOV_CROSSING_DESTROYED = "MOV_CROSSING_DESTROYED"
    CMB_ATTACKER_WIN = "CMB_ATTACKER_WIN"
    CMB_DEFENDER_WIN = "CMB_DEFENDER_WIN"
    CMB_STALEMATE = "CMB_STALEMATE"
    CMB_DEFENDER_FORTIFIED = "CMB_DEFENDER_FORTIFIED"
    CMB_TERRAIN_FAVORS_DEFENDER = "CMB_TERRAIN_FAVORS_DEFENDER"
    CMB_ATTACKER_LOW_SUPPLY = "CMB_ATTACKER_LOW_SUPPLY"
    CMB_FIRES_SUPPORT_APPLIED = "CMB_FIRES_SUPPORT_APPLIED"
    SUP_OK = "SUP_OK"
    SUP_LOW = "SUP_LOW"
    SUP_CRITICAL = "SUP_CRITICAL"
    SUP_ISOLATED = "SUP_ISOLATED"
    SUP_RESUPPLY_DELIVERED = "SUP_RESUPPLY_DELIVERED"
    CTL_DOMINANCE_BLUE = "CTL_DOMINANCE_BLUE"
    CTL_DOMINANCE_RED = "CTL_DOMINANCE_RED"
    CTL_CONTESTED = "CTL_CONTESTED"
    CTL_PERSISTENCE_THRESHOLD = "CTL_PERSISTENCE_THRESHOLD"
    VAL_UNIT_NOT_FOUND = "VAL_UNIT_NOT_FOUND"
    VAL_UNIT_NOT_OWNED = "VAL_UNIT_NOT_OWNED"
    VAL_UNIT_DESTROYED = "VAL_UNIT_DESTROYED"
    VAL_ACTION_ILLEGAL_FOR_UNIT = "VAL_ACTION_ILLEGAL_FOR_UNIT"
    VAL_TARGET_INVALID = "VAL_TARGET_INVALID"
    VAL_OUT_OF_RANGE = "VAL_OUT_OF_RANGE"
    VAL_UNIT_LACKS_OFFENSIVE_CAPABILITY = "VAL_UNIT_LACKS_OFFENSIVE_CAPABILITY"
    SYS_TURN_ADVANCED = "SYS_TURN_ADVANCED"
    SYS_FALLBACK_HOLD = "SYS_FALLBACK_HOLD"
"""Canonical enums for the deterministic Kriegsspiel engine."""

from enum import Enum
